# Generated by Django 6.0.3 on 2026-03-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atrybut',
            name='podkategorie',
            field=models.ManyToManyField(blank=True, related_name='dostepne_atrybuty', to='sklep.podkategoria'),
        ),
    ]
