# Generated by Django 6.0.3 on 2026-03-21 21:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_atrybut_podkategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towar',
            name='opis',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
