# Generated by Django 6.0.3 on 2026-03-27 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0003_alter_towar_opis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='uwagi_wewnetrzne',
            field=models.TextField(blank=True, help_text='Notatki widoczne tylko w panelu pracownika', null=True),
        ),
        migrations.CreateModel(
            name='HistoriaStatusowZamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stary_status', models.CharField(blank=True, max_length=30, null=True)),
                ('nowy_status', models.CharField(max_length=30)),
                ('data_zmiany', models.DateTimeField(auto_now_add=True)),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia_statusow', to='sklep.zamowienie')),
                ('zmienione_przez', models.ForeignKey(blank=True, help_text='Konto pracownika (User), które zmieniło status', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historia statusu',
                'verbose_name_plural': 'Historie statusów',
                'db_table': 'historia_statusow_zamowienia',
                'ordering': ['-data_zmiany'],
            },
        ),
    ]
