# Generated by Django 6.0.3 on 2026-03-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0004_zamowienie_uwagi_wewnetrzne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='metoda_platnosci',
            field=models.CharField(default='PRZELEW', max_length=50),
        ),
    ]
