# Generated by Django 6.0.3 on 2026-03-27 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0005_zamowienie_metoda_platnosci'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZdjecieTowaru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(upload_to='towary_dodatkowe/')),
                ('towar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodatkowe_zdjecia', to='sklep.towar')),
            ],
            options={
                'verbose_name': 'Dodatkowe Zdjęcie',
                'verbose_name_plural': 'Dodatkowe Zdjęcia',
                'db_table': 'zdjecia_towarow',
            },
        ),
    ]
