# Generated by Django 6.0.3 on 2026-03-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0006_zdjecietowaru'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinia',
            name='data_odpowiedzi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opinia',
            name='odpowiedz_pracownika',
            field=models.TextField(blank=True, null=True),
        ),
    ]
