# Generated by Django 6.0.3 on 2026-03-27 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0007_opinia_data_odpowiedzi_opinia_odpowiedz_pracownika'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodaPlatnosci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('aktywna', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Metoda płatności',
                'verbose_name_plural': 'Metody płatności',
                'db_table': 'metody_platnosci',
            },
        ),
        migrations.AlterField(
            model_name='platnosc',
            name='metoda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklep.metodaplatnosci'),
        ),
    ]
