# Generated by Django 6.0.3 on 2026-03-27 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0008_metodaplatnosci_alter_platnosc_metoda'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdpowiedzNaReklamacje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_odpowiedzi', models.DateTimeField(auto_now_add=True)),
                ('reklamacja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odpowiedz_sklepu', to='sklep.reklamacja')),
            ],
            options={
                'verbose_name': 'Odpowiedź na reklamację',
                'verbose_name_plural': 'Odpowiedzi na reklamacje',
                'db_table': 'odpowiedzi_na_reklamacje',
            },
        ),
    ]
