# Generated by Django 6.0.3 on 2026-03-27 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0009_odpowiedznareklamacje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklamacja',
            name='pozycja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reklamacje', to='sklep.pozycjazamowienia'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WiadomoscReklamacji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('autor', models.CharField(choices=[('SKLEP', 'Sklep'), ('KLIENT', 'Klient')], max_length=10)),
                ('data_wyslania', models.DateTimeField(auto_now_add=True)),
                ('reklamacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiadomosci', to='sklep.reklamacja')),
            ],
            options={
                'verbose_name': 'Wiadomość reklamacji',
                'verbose_name_plural': 'Wiadomości reklamacji',
                'db_table': 'wiadomosci_reklamacji',
                'ordering': ['data_wyslania'],
            },
        ),
        migrations.DeleteModel(
            name='OdpowiedzNaReklamacje',
        ),
    ]
